name: cheqd-node 3.0.1 test

on: [pull_request, push]
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      CHEQD_MNEMONIC: "sketch mountain erode window enact net enrich smoke claim kangaroo another visual write meat latin bacon pulp similar forum guilt father state erase bright"
      IMAGE_TAG: "3.0.1"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "20.x"
      - run: yarn install --frozen-lockfile --ignore-scripts
      - run: npm install -g turbo@2.0.5
      - run: turbo telemetry disable
      - run: CHEQD_MNEMONIC=$CHEQD_MNEMONIC yarn test
